package report

/*
	Report package works with windup report data. It can parse the JSON report data
	generated by windup and convert it into equivalent analyzer violations report.
	It also provides functions to compare violations.

	Note that windup needs the reporting-data addon (6.2.4+) to generate JSON reports.
*/
