name: 'Build and Push Multi-Arch Image'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release-*'
    tags:
      - 'v*'

concurrency:
  group: march-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-quay:
    name: Build and Push Manifest
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
    - name: Checkout Push to Registry action
      uses: konveyor/release-tools/build-push-quay@main
      with:
        architectures: "amd64, arm64, ppc64le, s390x"
        containerfile: "./core.Dockerfile"
        image_name: "windup-shim"
        image_namespace: "konveyor"
        image_registry: "quay.io"
        pre_build_cmd: |
          TAG=${GITHUB_REF_NAME/main/latest}
          sed -i "s,FROM quay.io/konveyor/analyzer-lsp,FROM quay.io/konveyor/analyzer-lsp:${TAG}," core.Dockerfile
        quay_publish_robot: ${{ secrets.QUAY_PUBLISH_ROBOT }}
        quay_publish_token: ${{ secrets.QUAY_PUBLISH_TOKEN }}
        ref: ${{ github.ref }}
